name: vc-env
dependencies:
 - python=3.6
 - numpy>=1.19.2
 - pandas>=1.1.5
 - scikit-learn>=0.22.2.post1
 - tqdm>=4.41.1
 - matplotlib>=3.2.2
 - plotly>=4.7.0,<4.14.3
 - seaborn

 - pip:
   - bertopic
   - flair==0.7
   - sentence-transformers>=0.4.1
   - umap-learn>=0.5.0
   - hdbscan>=0.8.27
   - torch>=1.4.0
   - nbformat>=4.2.0
   - openpyxl
   - ipykernel

